---
- hosts: webservers
  remote_user: felix
  sudo: yes
  tasks:
  - name: install vim 
    yum: name=vim state=latest
  - name: install mailx 
    yum: name=mailx state=latest
  - name: install bash-completion
    yum: name=bash-completion state=latest
 
  - name: install httpd 
    yum: name=httpd state=latest
    notify: 
     - restart apache
  - name: start httpd 
    service: name=httpd state=started enabled=yes
  - name: start firewalld
    service: name=firewalld state=started enabled=yes
  - name: install 
  handlers:
  - name: restart apache
    service: name=httpd state=restarted
...
